#!/bin/sh


# Linux 32
GOOS=linux CGO_ENABLED=1 go build -o  builds/skel/tmail

# zip
#cd builds/skel/
#zip -r ../../builds/linux/tmail.zip *
#cd ../../


# Sync
#rsync -vvv builds/linux/tmail.zip root@toorop.fr:/home/tmail/
rsync -vvv builds/skel/tmail root@toorop.fr:/home/tmail/
