#!/bin/sh


# Linux 64
GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o  /tmp/tmail & rsync -vvv /tmp/tmail root@smtp.tmail.io:/home/tmail/dist/tmail64

# 32
# Linux 64
#GOOS=linux GOARCH=386 CGO_ENABLED=1 go build -o  /tmp/tmail & rsync -vvv /tmp/tmail root@smtp.tmail.io:/home/tmail/dist/tmail

# zip
#cd builds/skel/
#zip -r ../../builds/linux/tmail.zip *
#cd ../../


# Sync
#rsync -vvv builds/linux/tmail.zip root@toorop.fr:/home/tmail/
# rsync -vvv /tmp/tmail root@smtp.tmail.io:/home/tmail/dist/tmail
