#!/bin/sh

. dist/conf/tmail.cfg

# Build

go build -o dist/tmail #&& dist/tmail user add 
dist/tmail
#dist/tmail user del toorop@tmail.io 
#dist/tmail user add toorop@tmail.io murphy25 -r -m
#dist/tmail relayip add 127.0.0.1
#dist/tmail relayip list
#dist/tmail relayip del 127.0.0.1
