// Code generated by protoc-gen-go.
// source: tmail.proto
// DO NOT EDIT!

/*
Package msproto is a generated protocol buffer package.

It is generated from these files:
	tmail.proto

It has these top-level messages:
	SmtpdResponse
	SmtpdNewClientMsg
	SmtpdRcpttoAccessIsGrantedQuery
	SmtpdRcpttoAccessIsGrantedResponse
	SmtpdDataMsg
	DeliverdGetRoutesQuery
	DeliverdGetRoutesResponse
*/
package msproto

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SmtpdResponse struct {
	SmtpCode         *int32   `protobuf:"varint,1,req,name=smtp_code" json:"smtp_code,omitempty"`
	SmtpMsg          *string  `protobuf:"bytes,2,req,name=smtp_msg" json:"smtp_msg,omitempty"`
	CloseConnection  *bool    `protobuf:"varint,16,opt,name=close_connection" json:"close_connection,omitempty"`
	DataLink         *string  `protobuf:"bytes,17,opt,name=data_link" json:"data_link,omitempty"`
	ExtraHeaders     []string `protobuf:"bytes,18,rep,name=extra_headers" json:"extra_headers,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SmtpdResponse) Reset()         { *m = SmtpdResponse{} }
func (m *SmtpdResponse) String() string { return proto.CompactTextString(m) }
func (*SmtpdResponse) ProtoMessage()    {}

func (m *SmtpdResponse) GetSmtpCode() int32 {
	if m != nil && m.SmtpCode != nil {
		return *m.SmtpCode
	}
	return 0
}

func (m *SmtpdResponse) GetSmtpMsg() string {
	if m != nil && m.SmtpMsg != nil {
		return *m.SmtpMsg
	}
	return ""
}

func (m *SmtpdResponse) GetCloseConnection() bool {
	if m != nil && m.CloseConnection != nil {
		return *m.CloseConnection
	}
	return false
}

func (m *SmtpdResponse) GetDataLink() string {
	if m != nil && m.DataLink != nil {
		return *m.DataLink
	}
	return ""
}

func (m *SmtpdResponse) GetExtraHeaders() []string {
	if m != nil {
		return m.ExtraHeaders
	}
	return nil
}

type SmtpdNewClientMsg struct {
	SessionId        *string `protobuf:"bytes,1,req,name=session_id" json:"session_id,omitempty"`
	RemoteIp         *string `protobuf:"bytes,2,req,name=remote_ip" json:"remote_ip,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SmtpdNewClientMsg) Reset()         { *m = SmtpdNewClientMsg{} }
func (m *SmtpdNewClientMsg) String() string { return proto.CompactTextString(m) }
func (*SmtpdNewClientMsg) ProtoMessage()    {}

func (m *SmtpdNewClientMsg) GetSessionId() string {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return ""
}

func (m *SmtpdNewClientMsg) GetRemoteIp() string {
	if m != nil && m.RemoteIp != nil {
		return *m.RemoteIp
	}
	return ""
}

// smtpdRcpttoAccessIsGranted
type SmtpdRcpttoAccessIsGrantedQuery struct {
	SessionId        *string `protobuf:"bytes,1,req,name=session_id" json:"session_id,omitempty"`
	Rcptto           *string `protobuf:"bytes,2,req,name=rcptto" json:"rcptto,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SmtpdRcpttoAccessIsGrantedQuery) Reset()         { *m = SmtpdRcpttoAccessIsGrantedQuery{} }
func (m *SmtpdRcpttoAccessIsGrantedQuery) String() string { return proto.CompactTextString(m) }
func (*SmtpdRcpttoAccessIsGrantedQuery) ProtoMessage()    {}

func (m *SmtpdRcpttoAccessIsGrantedQuery) GetSessionId() string {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return ""
}

func (m *SmtpdRcpttoAccessIsGrantedQuery) GetRcptto() string {
	if m != nil && m.Rcptto != nil {
		return *m.Rcptto
	}
	return ""
}

// SmtpdRcpttoAccessIsGrantedResponse
type SmtpdRcpttoAccessIsGrantedResponse struct {
	SessionId        *string `protobuf:"bytes,1,req,name=session_id" json:"session_id,omitempty"`
	RelayGranted     *bool   `protobuf:"varint,2,req,name=relay_granted" json:"relay_granted,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SmtpdRcpttoAccessIsGrantedResponse) Reset()         { *m = SmtpdRcpttoAccessIsGrantedResponse{} }
func (m *SmtpdRcpttoAccessIsGrantedResponse) String() string { return proto.CompactTextString(m) }
func (*SmtpdRcpttoAccessIsGrantedResponse) ProtoMessage()    {}

func (m *SmtpdRcpttoAccessIsGrantedResponse) GetSessionId() string {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return ""
}

func (m *SmtpdRcpttoAccessIsGrantedResponse) GetRelayGranted() bool {
	if m != nil && m.RelayGranted != nil {
		return *m.RelayGranted
	}
	return false
}

// smtpdDataMsg
type SmtpdDataMsg struct {
	SessionId        *string `protobuf:"bytes,1,req,name=session_id" json:"session_id,omitempty"`
	DataLink         *string `protobuf:"bytes,2,req,name=data_link" json:"data_link,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SmtpdDataMsg) Reset()         { *m = SmtpdDataMsg{} }
func (m *SmtpdDataMsg) String() string { return proto.CompactTextString(m) }
func (*SmtpdDataMsg) ProtoMessage()    {}

func (m *SmtpdDataMsg) GetSessionId() string {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return ""
}

func (m *SmtpdDataMsg) GetDataLink() string {
	if m != nil && m.DataLink != nil {
		return *m.DataLink
	}
	return ""
}

// Get routes query
type DeliverdGetRoutesQuery struct {
	DeliverdId       *string `protobuf:"bytes,1,req,name=deliverd_id" json:"deliverd_id,omitempty"`
	Mailfrom         *string `protobuf:"bytes,2,req,name=mailfrom" json:"mailfrom,omitempty"`
	Rcptto           *string `protobuf:"bytes,3,req,name=rcptto" json:"rcptto,omitempty"`
	AuthentifiedUser *string `protobuf:"bytes,4,opt,name=authentified_user" json:"authentified_user,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeliverdGetRoutesQuery) Reset()         { *m = DeliverdGetRoutesQuery{} }
func (m *DeliverdGetRoutesQuery) String() string { return proto.CompactTextString(m) }
func (*DeliverdGetRoutesQuery) ProtoMessage()    {}

func (m *DeliverdGetRoutesQuery) GetDeliverdId() string {
	if m != nil && m.DeliverdId != nil {
		return *m.DeliverdId
	}
	return ""
}

func (m *DeliverdGetRoutesQuery) GetMailfrom() string {
	if m != nil && m.Mailfrom != nil {
		return *m.Mailfrom
	}
	return ""
}

func (m *DeliverdGetRoutesQuery) GetRcptto() string {
	if m != nil && m.Rcptto != nil {
		return *m.Rcptto
	}
	return ""
}

func (m *DeliverdGetRoutesQuery) GetAuthentifiedUser() string {
	if m != nil && m.AuthentifiedUser != nil {
		return *m.AuthentifiedUser
	}
	return ""
}

// get routes response
type DeliverdGetRoutesResponse struct {
	DeliverdId       *string                            `protobuf:"bytes,1,req,name=deliverd_id" json:"deliverd_id,omitempty"`
	Routes           []*DeliverdGetRoutesResponse_Route `protobuf:"bytes,2,rep,name=routes" json:"routes,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *DeliverdGetRoutesResponse) Reset()         { *m = DeliverdGetRoutesResponse{} }
func (m *DeliverdGetRoutesResponse) String() string { return proto.CompactTextString(m) }
func (*DeliverdGetRoutesResponse) ProtoMessage()    {}

func (m *DeliverdGetRoutesResponse) GetDeliverdId() string {
	if m != nil && m.DeliverdId != nil {
		return *m.DeliverdId
	}
	return ""
}

func (m *DeliverdGetRoutesResponse) GetRoutes() []*DeliverdGetRoutesResponse_Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type DeliverdGetRoutesResponse_Route struct {
	RemoteHost       *string `protobuf:"bytes,1,req,name=remote_host" json:"remote_host,omitempty"`
	RemotePort       *int64  `protobuf:"varint,2,req,name=remote_port" json:"remote_port,omitempty"`
	LocalIp          *string `protobuf:"bytes,3,opt,name=local_ip" json:"local_ip,omitempty"`
	Priority         *int32  `protobuf:"varint,4,opt,name=priority" json:"priority,omitempty"`
	SmtpauthLogin    *string `protobuf:"bytes,5,opt,name=smtpauth_login" json:"smtpauth_login,omitempty"`
	SmtpauthPassword *string `protobuf:"bytes,6,opt,name=smtpauth_password" json:"smtpauth_password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeliverdGetRoutesResponse_Route) Reset()         { *m = DeliverdGetRoutesResponse_Route{} }
func (m *DeliverdGetRoutesResponse_Route) String() string { return proto.CompactTextString(m) }
func (*DeliverdGetRoutesResponse_Route) ProtoMessage()    {}

func (m *DeliverdGetRoutesResponse_Route) GetRemoteHost() string {
	if m != nil && m.RemoteHost != nil {
		return *m.RemoteHost
	}
	return ""
}

func (m *DeliverdGetRoutesResponse_Route) GetRemotePort() int64 {
	if m != nil && m.RemotePort != nil {
		return *m.RemotePort
	}
	return 0
}

func (m *DeliverdGetRoutesResponse_Route) GetLocalIp() string {
	if m != nil && m.LocalIp != nil {
		return *m.LocalIp
	}
	return ""
}

func (m *DeliverdGetRoutesResponse_Route) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *DeliverdGetRoutesResponse_Route) GetSmtpauthLogin() string {
	if m != nil && m.SmtpauthLogin != nil {
		return *m.SmtpauthLogin
	}
	return ""
}

func (m *DeliverdGetRoutesResponse_Route) GetSmtpauthPassword() string {
	if m != nil && m.SmtpauthPassword != nil {
		return *m.SmtpauthPassword
	}
	return ""
}

func init() {
}
